/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.JFrame;
import javax.swing.JPanel;



/**
 *
 * @author My PC
 */
public class FrmMenu extends javax.swing.JFrame {
    private JPanel childPanel;

    /**
     * Creates new form NewJFrame
     */
    public FrmMenu() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        mnuMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mniQuanLyKh = new javax.swing.JMenuItem();
        mniTimKiemKH = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ SHOP BÁN HÀNG QUẦN ÁO");
        setPreferredSize(new java.awt.Dimension(800, 631));

        pnlMain.setLayout(new java.awt.BorderLayout());

        mnuMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mnuMenu.setPreferredSize(new java.awt.Dimension(20, 80));

        jMenu1.setForeground(new java.awt.Color(0, 153, 153));
        jMenu1.setIcon(new javax.swing.ImageIcon("D:\\HK6\\PTUD\\DeTai_Nhom4\\img\\system-update (1).png")); // NOI18N
        jMenu1.setText("Hệ thống");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenu1.setIconTextGap(-90);
        jMenu1.setMinimumSize(new java.awt.Dimension(180, 22));
        jMenu1.setMultiClickThreshhold(10L);
        jMenu1.setPreferredSize(new java.awt.Dimension(200, 22));

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem1.setIcon(new javax.swing.ImageIcon("D:\\HK6\\PTUD\\DeTai_Nhom4\\img\\check-out.png")); // NOI18N
        jMenuItem1.setText("Đăng xuất");
        jMenuItem1.setPreferredSize(new java.awt.Dimension(230, 30));
        jMenuItem1.setSelected(true);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem2.setIcon(new javax.swing.ImageIcon("D:\\HK6\\PTUD\\DeTai_Nhom4\\img\\remove.png")); // NOI18N
        jMenuItem2.setText("Thoát");
        jMenuItem2.setPreferredSize(new java.awt.Dimension(230, 30));
        jMenuItem2.setSelected(true);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        mnuMenu.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 153, 153));
        jMenu2.setIcon(new javax.swing.ImageIcon("D:\\HK6\\PTUD\\DeTai_Nhom4\\img\\man.png")); // NOI18N
        jMenu2.setText("Nhân viên");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenu2.setIconTextGap(-90);
        jMenu2.setPreferredSize(new java.awt.Dimension(200, 22));

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem3.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem3.setIcon(new javax.swing.ImageIcon("D:\\HK6\\PTUD\\DeTai_Nhom4\\img\\planning.png")); // NOI18N
        jMenuItem3.setText("Quản lý nhân viên");
        jMenuItem3.setPreferredSize(new java.awt.Dimension(230, 30));
        jMenuItem3.setSelected(true);
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem4.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem4.setIcon(new javax.swing.ImageIcon("D:\\HK6\\PTUD\\DeTai_Nhom4\\img\\search.png")); // NOI18N
        jMenuItem4.setText("Tìm kiếm nhân viên");
        jMenuItem4.setPreferredSize(new java.awt.Dimension(230, 30));
        jMenuItem4.setSelected(true);
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        mnuMenu.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(0, 153, 153));
        jMenu3.setIcon(new javax.swing.ImageIcon("D:\\HK6\\PTUD\\DeTai_Nhom4\\img\\male-clothes.png")); // NOI18N
        jMenu3.setText("Sản phẩm");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenu3.setIconTextGap(-90);
        jMenu3.setPreferredSize(new java.awt.Dimension(200, 22));

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem5.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem5.setIcon(new javax.swing.ImageIcon("D:\\HK6\\PTUD\\DeTai_Nhom4\\img\\planning.png")); // NOI18N
        jMenuItem5.setText("Quản lý sản phẩm");
        jMenuItem5.setPreferredSize(new java.awt.Dimension(230, 30));
        jMenuItem5.setSelected(true);
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem6.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem6.setIcon(new javax.swing.ImageIcon("D:\\HK6\\PTUD\\DeTai_Nhom4\\img\\search.png")); // NOI18N
        jMenuItem6.setText("Tìm kiếm sản phẩm");
        jMenuItem6.setPreferredSize(new java.awt.Dimension(230, 30));
        jMenuItem6.setSelected(true);
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        mnuMenu.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(0, 153, 153));
        jMenu4.setIcon(new javax.swing.ImageIcon("D:\\HK6\\PTUD\\DeTai_Nhom4\\img\\youth.png")); // NOI18N
        jMenu4.setText("Khách hàng");
        jMenu4.setToolTipText("");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenu4.setIconTextGap(-90);
        jMenu4.setPreferredSize(new java.awt.Dimension(200, 22));
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        mniQuanLyKh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mniQuanLyKh.setForeground(new java.awt.Color(0, 153, 153));
        mniQuanLyKh.setIcon(new javax.swing.ImageIcon("D:\\HK6\\PTUD\\DeTai_Nhom4\\img\\planning.png")); // NOI18N
        mniQuanLyKh.setText("Quản lý khách hàng");
        mniQuanLyKh.setPreferredSize(new java.awt.Dimension(230, 30));
        mniQuanLyKh.setSelected(true);
        mniQuanLyKh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQuanLyKhActionPerformed(evt);
            }
        });
        jMenu4.add(mniQuanLyKh);

        mniTimKiemKH.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mniTimKiemKH.setForeground(new java.awt.Color(0, 153, 153));
        mniTimKiemKH.setIcon(new javax.swing.ImageIcon("D:\\HK6\\PTUD\\DeTai_Nhom4\\img\\search.png")); // NOI18N
        mniTimKiemKH.setText("Tìm kiếm khách hàng");
        mniTimKiemKH.setPreferredSize(new java.awt.Dimension(230, 30));
        mniTimKiemKH.setSelected(true);
        mniTimKiemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTimKiemKHActionPerformed(evt);
            }
        });
        jMenu4.add(mniTimKiemKH);

        mnuMenu.add(jMenu4);

        jMenu5.setForeground(new java.awt.Color(0, 153, 153));
        jMenu5.setIcon(new javax.swing.ImageIcon("D:\\HK6\\PTUD\\DeTai_Nhom4\\img\\bill.png")); // NOI18N
        jMenu5.setText("Hóa đơn");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenu5.setIconTextGap(-90);
        jMenu5.setPreferredSize(new java.awt.Dimension(200, 22));

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem9.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem9.setIcon(new javax.swing.ImageIcon("D:\\HK6\\PTUD\\DeTai_Nhom4\\img\\invoice.png")); // NOI18N
        jMenuItem9.setText("Lập hóa đơn");
        jMenuItem9.setPreferredSize(new java.awt.Dimension(230, 30));
        jMenuItem9.setSelected(true);
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem10.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem10.setIcon(new javax.swing.ImageIcon("D:\\HK6\\PTUD\\DeTai_Nhom4\\img\\planning.png")); // NOI18N
        jMenuItem10.setText("Quản lý hóa đơn");
        jMenuItem10.setPreferredSize(new java.awt.Dimension(230, 30));
        jMenuItem10.setSelected(true);
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        mnuMenu.add(jMenu5);

        jMenu6.setForeground(new java.awt.Color(0, 153, 153));
        jMenu6.setIcon(new javax.swing.ImageIcon("D:\\HK6\\PTUD\\DeTai_Nhom4\\img\\revenue.png")); // NOI18N
        jMenu6.setText("Doanh thu");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenu6.setIconTextGap(-90);
        jMenu6.setPreferredSize(new java.awt.Dimension(200, 22));

        jMenuItem13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem13.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem13.setText("Doanh thu theo ngày");
        jMenuItem13.setPreferredSize(new java.awt.Dimension(230, 30));
        jMenuItem13.setSelected(true);
        jMenu6.add(jMenuItem13);

        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem11.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem11.setText("Doanh thu theo tháng");
        jMenuItem11.setPreferredSize(new java.awt.Dimension(230, 30));
        jMenuItem11.setSelected(true);
        jMenu6.add(jMenuItem11);

        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem12.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem12.setText("Doanh thu theo năm");
        jMenuItem12.setPreferredSize(new java.awt.Dimension(230, 30));
        jMenuItem12.setSelected(true);
        jMenu6.add(jMenuItem12);

        mnuMenu.add(jMenu6);

        setJMenuBar(mnuMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void mniQuanLyKhActionPerformed(java.awt.event.ActionEvent evt) {                                            
        ShowPanel(new PnlQuanLyKhachHang());
    }                                           

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        System.exit(1);
    }                                          

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {                                       

    }                                      

    private void mniTimKiemKHActionPerformed(java.awt.event.ActionEvent evt) {                                             
        ShowPanel(new PnlTimKH());
    }                                            

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        ShowPanel(new PnlLapHoaDon());
    }                                          

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        ShowPanel(new PnlQuanLyNhanVien());
    }                                          

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        ShowPanel(new PnlTimNV());
    }                                          

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {                                           
       ShowPanel(new PnlQuanLySanPham());
    }                                          

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {                                           
       ShowPanel(new PnlTimSP());
    }                                          

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        ShowPanel(new PnlQuanLyHoaDon());
    }                                           
    public void ShowPanel(JPanel panel){
        childPanel = panel;
        pnlMain.removeAll();
        pnlMain.add(childPanel);
        pnlMain.validate();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }
            
    

    // Variables declaration - do not modify                     
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem mniQuanLyKh;
    private javax.swing.JMenuItem mniTimKiemKH;
    private javax.swing.JMenuBar mnuMenu;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration                   


}
